[[FLEXPART]]
arch = "aarch64"
git-tree-sha1 = "e5f6ba28ac0ff7567b85acd2f7fc4f40ce978831"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FLEXPART.download]]
    sha256 = "c9bff36df9a2a49b870efd2f5c72339b60a9b4171bca0799e320ad6b37269cbe"
    url = "https://github.com/JuliaBinaryWrappers/FLEXPART_jll.jl/releases/download/FLEXPART-v11.0.0+0/FLEXPART.v11.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FLEXPART]]
arch = "x86_64"
git-tree-sha1 = "7c1a3c65d7071f7f0da965a8e7f1814cd8e16326"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FLEXPART.download]]
    sha256 = "95c6f7626e13c5ceebb599ea77dfb48dddff1bc7fe922e1e68f2dc575df976fe"
    url = "https://github.com/JuliaBinaryWrappers/FLEXPART_jll.jl/releases/download/FLEXPART-v11.0.0+0/FLEXPART.v11.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
